spring.application.name=VaultCore

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (ORACLE)
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:FREE
spring.datasource.username=system
spring.datasource.password=Oracle123!
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
# Muestra en la consola las consultas SQL que Spring hace por debajo
spring.jpa.show-sql=true

# basándose en tus clases de Java (como la clase Cuenta)
spring.jpa.hibernate.ddl-auto=update